import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Stack, NewBox } from "../ui/EveryLayout";
import Carousel from "../components/Carousel";
import Genres from "../lib/Genres";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blockbuster</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Stack backgroundColor="var(--color-light-purple)">
        {Genres.map((genre: string) => (
          <NewBox key={genre}>
            <Link href={`/genre/${genre.toLowerCase()}`} passHref>
              <a>
                <h1>{genre}</h1>
              </a>
            </Link>
            <button>Movies</button>
            <button>Series</button>
            <Link href={`/genre/${genre}`} passHref>
              <a>
                <button>See all</button>
              </a>
            </Link>
            <Carousel genre={genre} />
          </NewBox>
        ))}
      </Stack>
    </>
  );
};

export default Home;
