import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Stack } from "../ui/EveryLayout";

const Home: NextPage = () => {
  return (
    <Stack>
      <Head>
        <title>Blockbuster</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
    </Stack>
  );
};

export default Home;
